### ISSUE TITLE
Lol you just copied the Laravel Readme

### ISSUE THREAD

**Issue by sayopaul** [shalvah/botrivia#1]
Hello , I have been following your tutorial on medium and errm I came to your repo but i would like to say the readme is very very misleading lol > Maybe just talk about bottrivia, why you came up with it , etc . Also, maybe you should get rid of things you are not going to use like the welcome.blade.php that comes with new laravel installations . Great job though bro

**Comment by shalvah** [comment]
True. Thanks for pointing it out. I'll get to that. I was so tired that
night I just focused on finishing the article and ensuring that stuff
worked.
